export default {
  // Auth
  AUTH_TEXT_CHANGED: 'AUTH_TEXT_CHANGED',
  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  SIGNUP_USER_REQUEST: 'SIGNUP_USER_REQUEST',
  SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
  SIGNUP_USER_FAIL: 'SIGNUP_USER_FAIL',

  // Page
  PAGE_TEXT_CHANGED: 'PAGE_TEXT_CHANGED',
  PAGE_SCHEDULE_CHANGED: 'PAGE_SCHEDULE_CHANGED',
  EMPLOYEE_SAVE: 'EMPLOYEE_SAVE',
  EMPLOYEE_UPDATE: 'EMPLOYEE_UPDATE',
  EMPLOYEE_FIRE: 'EMPLOYEE_FIRE',

  // Employees
  GET_EMPLOYEES_LIST: 'GET_EMPLOYEES_LIST',
  LISTEN_TO_EMPLOYEES: 'LISTEN_TO_EMPLOYEES',
  UPDATE_EMPLOYEES_LIST: 'UPDATE_EMPLOYEES_LIST',

  // Server
  CONNECTING_TO_SERVER: 'CONNECTING_TO_SERVER',
  DISCONNECTED_FROM_SERVER: 'DISCONNECTED_FROM_SERVER',
};
