export default {
  EMAIL_TEXT_CHANGED: 'EMAIL_TEXT_CHANGED',
  PASSWORD_TEXT_CHANGED: 'PASSWORD_TEXT_CHANGED',
  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  SIGNUP_USER_REQUEST: 'SIGNUP_USER_REQUEST',
  SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
  SIGNUP_USER_FAIL: 'SIGNUP_USER_FAIL',
  CONNECTING_TO_SERVER: 'CREATING_NEW_USER'
}